### ISSUE TITLE
No tracker information after transfer.

### ISSUE THREAD

**Issue by Misiek304** [mikedld/bt-migrate#1]
After transfering .torrents from uTorrent to Transmission there is no information about trackers in Transmission. I guess this is caused because uTorrent doesn't save tracker information inside .torrent files (that's stupid). Instead information about trackers are kept inside resume.dat file. 

Could you maybe tweak your tool to fix that?

**Comment by mikedld** [comment]
Thanks for reporting this. I'm planning to get back to this project soon, will see what I can do.
