### ISSUE TITLE
Deluge to Transmission: Pickle opcode 128 not yet supported

### ISSUE THREAD

**Issue by JosephDuffy** [mikedld/bt-migrate#12]
When running `./BtMigrate --source deluge --source-dir ./Deluge/config/ --target transmission --target-dir ./Transmission/` I get the following output:

```
[2020-Mar-07 15:17:15.972061] [I] Source: Deluge ("/home/user/.config/Deluge/config")
[2020-Mar-07 15:17:15.972133] [I] Target: Transmission ("/home/user/.config/Transmission")
[2020-Mar-07 15:17:15.975322] [E] Error: Pickle opcode 128 not yet supported
[2020-Mar-07 15:17:15.975369] [E] Error: Pickle opcode 128 not yet supported
```

I see this on macOS and Ubuntu, and haven't been able to find any further information about this error.

I'm guessing there's something in my data that's causing this, but I'm not sure how to track it down?

**Comment by mikedld** [comment]
Please check out #13 (could use pre-built binaries from https://github.com/mikedld/bt-migrate/actions/runs/51437498) to see if it helps.

**Comment by JosephDuffy** [comment]
> Please check out #13 (could use pre-built binaries from [mikedld/bt-migrate/actions/runs/51437498](https://github.com/mikedld/bt-migrate/actions/runs/51437498)) to see if it helps.

Thanks, I'll subscribe to that issue :)

I should've mentioned in my original comment that I tried the pre-compiled binaries for both macOS and Ubuntu (along with locally compliled binaries) and they all show this error.

**Comment by mikedld** [comment]
Added support for `LONG_BINPUT` (114) opcode. Extended my test data a bit to reproduce but didn't hit any other opcodes, so please try again on your end.

**Comment by JosephDuffy** [comment]
> Added support for `LONG_BINPUT` (114) opcode. Extended my test data a bit to reproduce but didn't hit any other opcodes, so please try again on your end. New build at [mikedld/bt-migrate/actions/runs/51471269](https://github.com/mikedld/bt-migrate/actions/runs/51471269)

This build fails with `Error: Pickle opcode 133 not yet supported`.

I wish I could help with the fix, I don't even know where to start! Thank you for looking in to this :)

**Comment by mikedld** [comment]
Wasn't able to reproduce this one, so added support for `TUPLE1` (133), as well as `TUPLE2` (134) and `TUPLE3` (135), blindly. Hit `LONG_BINGET` (106) while testing so added support for that one too. Your turn ;) If it doesn't work now, consider sending me (directly) your `torrents.state` file.

**Comment by JosephDuffy** [comment]
> Wasn't able to reproduce this one, so added support for `TUPLE1` (133), as well as `TUPLE2` (134) and `TUPLE3` (135), blindly. Hit `LONG_BINGET` (106) while testing so added support for that one too. Your turn ;) If it doesn't work now, consider sending me (directly) your `torrents.state` file.
> 
> New build at [mikedld/bt-migrate/actions/runs/51678929](https://github.com/mikedld/bt-migrate/actions/runs/51678929)

Thanks works perfectly, thank you 🙌
