### ISSUE TITLE
Newbie problem installing - SQLITE3

### ISSUE THREAD

**Issue by aleczk** [mikedld/bt-migrate#14]
So, I basically know nothing about CMD, but I'm trying to change desperately from uTorrent to Transmission.

I've been in the past hours trying to install the cmake and boost (which I've never even knew it existed). Installed the VS Code, etc.

When I finally thought I did it... It didn't work. I have no idea why, I even tried to install SQLITE3 but no deal, to be honest I'm not even sure if I know who to do it.

Also I have no idea of how to use commands like find_package, etc which I found on almost all solutions but for me that's hebrew.

Anyone could please help me?

![image](https://user-images.githubusercontent.com/16522249/77709003-736e0380-6fa8-11ea-8a38-b08d830236dd.png)

[CMakeError.log](https://github.com/mikedld/bt-migrate/files/4390781/CMakeError.log)
[CMakeOutput.log](https://github.com/mikedld/bt-migrate/files/4390782/CMakeOutput.log)

**Comment by mikedld** [comment]
If you don't really want to build it but just use it, you could try grabbing the binary for your platform from the latest build on the Actions tab above, e.g. this one from master: https://github.com/mikedld/bt-migrate/actions/runs/51752466

**Comment by aleczk** [comment]
You are my savior! Finally did it. Had to download the SQLITE3.dll and put into System32 because I probably screwed it up before, but it worked like a charm.

`BtMigrate.exe --source uTorrent --source-dir=C:\Users\alecs\AppData\Roaming\uTorrent --target Transmission --target-dir=C:\Users\alecs\AppData\Local\transmission`
`[..]`
`[2020-Mar-27 08:36:16.121945] [I] Finished: 163 succeeded, 0 failed, 0 skipped`

**Comment by aleczk** [comment]
Any way you could upload the binaries for Windows again?

I had to format the damn Windows and lost the files and now they are expired :(. Sorry for the inconvenience...

**Comment by mikedld** [comment]
Hmm, let me think of something (I guess I'll have to make a commit for this). Should probably just make a release :)

**Comment by aleczk** [comment]
Thank you so much, again! Sorry to bother you being such a newbie with these things. 

I spent like 1:30 installing VS, Cmake and SQLite3 before I asked for help because I'm such a dumbass.

Obrigado!

> [2021-Jan-04 19:01:22.960794] [I] Finished: 220 succeeded, 0 failed, 0 skipped
> [2021-Jan-04 19:01:22.961294] [I] Committing changes
