### ISSUE TITLE
Error: More than one torrent client matched data directory

### ISSUE THREAD

**Issue by singulararmchair** [mikedld/bt-migrate#15]
Trying to migrate from uTorrent to Transmission. 
iMac (21.5-inch, Late 2009)
Mac OS 10.13.6 (17G13033)

I made aliases for the source and destination as suggested in an older thread:
`./BtMigrate --source uTorrent --source-dir=/tmp/bt-src --target-dir=/tmp/bt-dst
`

Result:
> [2020-Jun-06 18:35:35.895159] [I] Source: uTorrent ("/Users/xxx/Library/Application Support/uTorrent")
> [2020-Jun-06 18:35:35.895473] [E] Error: More than one torrent client matched data directory

Same thing if I use the full paths instead of aliases.
What causes this? (I've double-checked and the links work fine)

**Comment by mikedld** [comment]
Try specifying target explicitly, i.e. passing `--target Transmission` or `--target TransmissionMac`.

**Comment by singulararmchair** [comment]
It worked! Thank you. Should've done this years ago lol
