### ISSUE TITLE
Can't migrate from uTorrent

### ISSUE THREAD

**Issue by waltercruz** [mikedld/bt-migrate#2]
on Mac OS 10.11

./bt-migrate --source utorrent --source-dir=/Users/waltercruz/Library/Application\ Support/uTorrent/ --target-dir ~/.config/transmission --dry-run --verbose

**Comment by waltercruz** [comment]
[2016-Feb-29 10:37:46.561257] [E] Error: the argument ('/Users/waltercruz/Library/Application Support/uTorrent/') for option '--source-dir' is invalid

**Comment by mikedld** [comment]
I saw this a while ago and search led me to [this boost defect](https://svn.boost.org/trac/boost/ticket/7704). Are you using boost 1.53 or below (issue seems to be fixed in 1.54)?

**Comment by waltercruz** [comment]
boost 1.60, installed through homebrew.

**Comment by waltercruz** [comment]
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   locale
--   program_options
--   system
-- JsonCpp Version: 0.6.0-dev
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/waltercruz/devel/bt-migrate

**Comment by mikedld** [comment]
Seems like they either didn't fix it or have broken it (or something else) again... I'll switch to `std::string` instead of `boost::filesystem::path` for options parsing then.

**Comment by mikedld** [comment]
Forgot to mention that the workaround for now would be to use paths of about 20 chars in length. You could try this:
```
# ln -s ~/Library/Application\ Support/uTorrent /tmp/bt-src
# ln -s ~/.config/transmission /tmp/bt-dst
# ./bt-migrate --source utorrent --source-dir=/tmp/bt-src --target-dir=/tmp/bt-dst --dry-run --verbose
```

**Comment by waltercruz** [comment]
created the links, and tried to run.
```
[ waltercruz stark0 ~/devel/bt-migrate ] ./bt-migrate --source utorrent --source-dir=/tmp/bt-src --target-dir=/tmp/bt-dst --dry-run --verbose
[2016-Feb-29 22:34:18.638212] [I] Source: uTorrent ("/Users/waltercruz/Library/Application Support/uTorrent")
[2016-Feb-29 22:34:18.639254] [E] Error: No torrent client matched data directory
```

maybe something is broken on my side :(

**Comment by mikedld** [comment]
Try passing `--target transmission` as well. If destination directory is empty it's hard to guess which client it's for :)

**Comment by waltercruz** [comment]
doens't work :(

BTW, the path for transmission files on mac now is ~/Library/Application\ Support/Transmission

But, even wth the right symlinks, it says.. "Import started", "Import succeeded"  for all files, but nothing is really imported.

**Comment by waltercruz** [comment]
Ouch, I found it! needs to load the .torrent file on transmission again. now it's working!

**Comment by rakudaniku** [comment]
I am getting a similar issue here, yet in the other direction.

```Comp:bt-migrate rakudaniku$ ./bt-migrate --source utorrent --source-dir=/tmp/bt-src --target-dir=/tmp/bt-dst --dry-run --verbose
[2017-May-16 21:10:30.548728] [I] Source: uTorrent ("/Users/rakudaniku/Library/Application Support/uTorrent")
[2017-May-16 21:10:30.549625] [E] Error: More than one torrent client matched data directory```

Is is a similar issue or should I make a new ticket for this?

**Comment by deweydb** [comment]
I'm having the same issue, I can't get this thing to work:
```
./BtMigrate --source uTorrent --source-dir /tmp/bt-src --target transmission --target-dir /tmp/bt-dst --dry-run --verbose
[2018-Feb-22 12:25:50.851504] [I] Source: uTorrent ("/Users/deweydb/Library/Application Support/uTorrent")
[2018-Feb-22 12:25:50.851966] [E] Error: Bad target data directory: "/Users/deweydb/.config/transmission"
```

**Comment by mikedld** [comment]
I've finally switched (see c8ebd6b21a383004dec2c51e96a50a8435f0ab53) to `std::string` in program options to workaround boost defect mentioned earlier. There was also a number of improvements like adding "TransmissionMac" target in addition to previous "Transmission" target, with former generating not only resume and torrent files (but in proper directories now!) but also Transfers.plist file which allows to avoid any manual actions after the migration. Please do test and see if it works.

Keep in mind that due to the change in resume and torrent files naming in currently unreleased version of Transmission, those files are generated with new-style names by default. See https://github.com/mikedld/bt-migrate/issues/6#issuecomment-500030280 to get the old names back if you're using 2.9x or older, which is most probably the case.

**Comment by j1warren** [comment]
Since transmission now supports labels, could you maybe implement exporting them from utorrent and importing them to transmission?

[https://github.com/transmission/transmission/pull/822](url)

**Comment by mikedld** [comment]
@waltercruz, are you okay with closing this?

**Comment by rakudaniku** [comment]
yes, thanks for asking.

**Comment by rakudaniku** [comment]
gdi, replied to this thinking it was another mail that I was waiting for… I'll go hang my head in shame in the corner.

**Comment by mikedld** [comment]
@j1warren, not merged which means it doesn't really officially support labels yet. Will consider after the merge, but worth creating a separate issue.

**Comment by waltercruz** [comment]
> @waltercruz, are you okay with closing this?

sure!
