### ISSUE TITLE
Imported torrents from rTorrent dont have their save paths set.

### ISSUE THREAD

**Issue by KyleSanderson** [mikedld/bt-migrate#6]
Ran
```
./BtMigrate --source rtorrent --source-dir ~/.session --target transmission --target-dir 
~/.config/transmission-daemon
```
Imported 4600 torrents, however they all default to the Downloads directory and not their existing save directories. Coming from rtorrent 0.9.6.

**Comment by mikedld** [comment]
This is because of the recent change in torrent state files naming, f4e0721df7319e722ddfbb4ad45c7fcfef65ca9f. Current behavior is as desired and won't be fixed. Revert the commit locally if you are targeting Transmission 2.9x and below.

**Comment by mikedld** [comment]
FYI I've added support for `BT_MIGRATE_TRANSMISSION_2_9X` environment variable in e9f32455e0b5eb329e11f5819975fce8039d1311 to avoid changing the code; just set it to any value when running BtMigrate to get old-style names. Default behavior is still to generate new-style names (i.e. hash only).
