### ISSUE TITLE
deluge to transmission mapped_files not found

### ISSUE THREAD

**Issue by jgilfoil** [mikedld/bt-migrate#8]
So this is probably a bit of an edge case. I converted my uTorrent torrents from windows to deluge on windows. Than from deluge on windows to deluge on linux by modifying the paths with scripts (and that worked). Now i'm attempting to convert them from deluge to transmission but running into issues.

command used is:
```
./bt-migrate/BtMigrate --source deluge --source-dir /home/config --target Transmission --target /home/transmission-daemon/info --dry-run --verbose
```
The output is:
```
[2018-Jul-01 03:35:31.568581] [I] Source: Deluge ("/home/config")
[2018-Jul-01 03:35:31.568665] [I] Target: Transmission ("/home/transmission-daemon/info")
[2018-Jul-01 03:35:31.568683] [D] [Deluge] Loading torrents.fastresume
[2018-Jul-01 03:35:31.607886] [D] [Deluge] Loading torrents.state
terminate called after throwing an instance of 'jsoncons::json_exception_1<std::out_of_range>'
  what():  mapped_files not found
Aborted
```

**Comment by FigaroVL** [comment]
I had similar mistake. 
She arise with processing torrent files which in deluge don't have "Mapped Files" property.
i'm try fix this, but new path not correct - all file places at base patch in transmission.

**Comment by salazr** [comment]
Same issue here. I'm not sure how to set mapped_files in deluge.

**Comment by seanleblanc** [comment]
I have the same problem. Is there a known workaround?

**Comment by jgilfoil** [comment]
Sadly I never found a work around. I ended up leaving my existing torrents on deluge and started fresh with transmission with new torrents going forward.

**Comment by mikedld** [comment]
"mapped_files" key is now optional. That was the original intention, but I guess I need to start writing unit tests... Thanks everyone for reporting this.
